package com.indigocat.hockeyscoresheet.ui.theme
import androidx.compose.ui.graphics.Color

val light_primary = Color(0xFF00629D)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFFCFE5FF)
val light_onPrimaryContainer = Color(0xFF001D34)
val light_secondary = Color(0xFF006970)
val light_onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFF7FF4FF)
val light_onSecondaryContainer = Color(0xFF002022)
val light_tertiary = Color(0xFF1E5ABE)
val light_onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFFD9E2FF)
val light_onTertiaryContainer = Color(0xFF001944)
val light_error = Color(0xFFBA1A1A)
val light_errorContainer = Color(0xFFFFDAD6)
val light_onError = Color(0xFFFFFFFF)
val light_onErrorContainer = Color(0xFF410002)
val light_background = Color(0xFFFCFCFF)
val light_onBackground = Color(0xFF1A1C1E)
val light_surface = Color(0xFFFCFCFF)
val light_onSurface = Color(0xFF1A1C1E)
val light_surfaceVariant = Color(0xFFDEE3EB)
val light_onSurfaceVariant = Color(0xFF42474E)
val light_outline = Color(0xFF72777F)
val light_inverseOnSurface = Color(0xFFF1F0F4)
val light_inverseSurface = Color(0xFF2F3033)
val light_inversePrimary = Color(0xFF99CBFF)
val light_shadow = Color(0xFF000000)
val light_surfaceTint = Color(0xFF00629D)


val dark_primary = Color(0xFF99CBFF)
val dark_onPrimary = Color(0xFF003354)
val dark_primaryContainer = Color(0xFF004A78)
val dark_onPrimaryContainer = Color(0xFFCFE5FF)
val dark_secondary = Color(0xFF4DD9E5)
val dark_onSecondary = Color(0xFF00363B)
val dark_secondaryContainer = Color(0xFF004F55)
val dark_onSecondaryContainer = Color(0xFF7FF4FF)
val dark_tertiary = Color(0xFFB0C6FF)
val dark_onTertiary = Color(0xFF002D6E)
val dark_tertiaryContainer = Color(0xFF00429A)
val dark_onTertiaryContainer = Color(0xFFD9E2FF)
val dark_error = Color(0xFFFFB4AB)
val dark_errorContainer = Color(0xFF93000A)
val dark_onError = Color(0xFF690005)
val dark_onErrorContainer = Color(0xFFFFDAD6)
val dark_background = Color(0xFF1A1C1E)
val dark_onBackground = Color(0xFFE2E2E5)
val dark_surface = Color(0xFF1A1C1E)
val dark_onSurface = Color(0xFFE2E2E5)
val dark_surfaceVariant = Color(0xFF42474E)
val dark_onSurfaceVariant = Color(0xFFC2C7CF)
val dark_outline = Color(0xFF8C9199)
val dark_inverseOnSurface = Color(0xFF1A1C1E)
val dark_inverseSurface = Color(0xFFE2E2E5)
val dark_inversePrimary = Color(0xFF00629D)
val dark_shadow = Color(0xFF000000)
val dark_surfaceTint = Color(0xFF99CBFF)


val seed = Color(0xFF0072B5)

val penalty = Color(0xFFC4001B)
val light_penalty = Color(0xFFC0001A)
val light_onPenalty = Color(0xFFFFFFFF)
val light_penaltyContainer = Color(0xFFFFDAD6)
val light_onPenaltyContainer = Color(0xFF410003)
val dark_penalty = Color(0xFFFFB3AD)
val dark_onPenalty = Color(0xFF680009)
val dark_penaltyContainer = Color(0xFF930011)
val dark_onPenaltyContainer = Color(0xFFFFDAD6)

val light_goal = Color(0xFF006D31)
val light_onGoal = Color(0xFFFFFFFF)
val light_goalContainer = Color(0xFF88FAA1)
val light_onGoalContainer = Color(0xFF00210A)
val dark_goal = Color(0xFF6BDD87)
val dark_onGoal = Color(0xFF003916)
val dark_goalContainer = Color(0xFF005324)
val dark_onGoalContainer = Color(0xFF88FAA1)

