package com.indigocat.hockeyscoresheet.ui.theme
import androidx.compose.ui.graphics.Color

val light_primary = Color(0xFF3E4ADE)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFFE0E0FF)
val light_onPrimaryContainer = Color(0xFF000469)
val light_secondary = Color(0xFF00658E)
val light_onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFFC7E7FF)
val light_onSecondaryContainer = Color(0xFF001E2E)
val light_tertiary = Color(0xFF275DAE)
val light_onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFFD7E2FF)
val light_onTertiaryContainer = Color(0xFF001A40)
val light_error = Color(0xFFBA1A1A)
val light_errorContainer = Color(0xFFFFDAD6)
val light_onError = Color(0xFFFFFFFF)
val light_onErrorContainer = Color(0xFF410002)
val light_background = Color(0xFFFFFBFF)
val light_onBackground = Color(0xFF1B1B1F)
val light_surface = Color(0xFFFFFBFF)
val light_onSurface = Color(0xFF1B1B1F)
val light_surfaceVariant = Color(0xFFE3E1EC)
val light_onSurfaceVariant = Color(0xFF46464F)
val light_outline = Color(0xFF777680)
val light_inverseOnSurface = Color(0xFFF3F0F4)
val light_inverseSurface = Color(0xFF303034)
val light_inversePrimary = Color(0xFFBEC2FF)
val light_shadow = Color(0xFF000000)
val light_surfaceTint = Color(0xFF3E4ADE)

val dark_primary = Color(0xFFBEC2FF)
val dark_onPrimary = Color(0xFF000BA6)
val dark_primaryContainer = Color(0xFF202CC7)
val dark_onPrimaryContainer = Color(0xFFE0E0FF)
val dark_secondary = Color(0xFF85CFFF)
val dark_onSecondary = Color(0xFF00344C)
val dark_secondaryContainer = Color(0xFF004C6C)
val dark_onSecondaryContainer = Color(0xFFC7E7FF)
val dark_tertiary = Color(0xFFACC7FF)
val dark_onTertiary = Color(0xFF002F67)
val dark_tertiaryContainer = Color(0xFF004491)
val dark_onTertiaryContainer = Color(0xFFD7E2FF)
val dark_error = Color(0xFFFFB4AB)
val dark_errorContainer = Color(0xFF93000A)
val dark_onError = Color(0xFF690005)
val dark_onErrorContainer = Color(0xFFFFDAD6)
val dark_background = Color(0xFF1B1B1F)
val dark_onBackground = Color(0xFFE5E1E6)
val dark_surface = Color(0xFF1B1B1F)
val dark_onSurface = Color(0xFFE5E1E6)
val dark_surfaceVariant = Color(0xFF46464F)
val dark_onSurfaceVariant = Color(0xFFC7C5D0)
val dark_outline = Color(0xFF91909A)
val dark_inverseOnSurface = Color(0xFF1B1B1F)
val dark_inverseSurface = Color(0xFFE5E1E6)
val dark_inversePrimary = Color(0xFF3E4ADE)
val dark_shadow = Color(0xFF000000)
val dark_surfaceTint = Color(0xFFBEC2FF)


val seed = Color(0xFF000EB9)
