package com.indigocat.hockeyscoresheet.ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF3E4ADE)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE0E0FF)
val md_theme_light_onPrimaryContainer = Color(0xFF000469)
val md_theme_light_secondary = Color(0xFF00658E)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFC7E7FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001E2E)
val md_theme_light_tertiary = Color(0xFF275DAE)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFD7E2FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001A40)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1B1B1F)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1B1B1F)
val md_theme_light_surfaceVariant = Color(0xFFE3E1EC)
val md_theme_light_onSurfaceVariant = Color(0xFF46464F)
val md_theme_light_outline = Color(0xFF777680)
val md_theme_light_inverseOnSurface = Color(0xFFF3F0F4)
val md_theme_light_inverseSurface = Color(0xFF303034)
val md_theme_light_inversePrimary = Color(0xFFBEC2FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF3E4ADE)

val md_theme_dark_primary = Color(0xFFBEC2FF)
val md_theme_dark_onPrimary = Color(0xFF000BA6)
val md_theme_dark_primaryContainer = Color(0xFF202CC7)
val md_theme_dark_onPrimaryContainer = Color(0xFFE0E0FF)
val md_theme_dark_secondary = Color(0xFF85CFFF)
val md_theme_dark_onSecondary = Color(0xFF00344C)
val md_theme_dark_secondaryContainer = Color(0xFF004C6C)
val md_theme_dark_onSecondaryContainer = Color(0xFFC7E7FF)
val md_theme_dark_tertiary = Color(0xFFACC7FF)
val md_theme_dark_onTertiary = Color(0xFF002F67)
val md_theme_dark_tertiaryContainer = Color(0xFF004491)
val md_theme_dark_onTertiaryContainer = Color(0xFFD7E2FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1B1B1F)
val md_theme_dark_onBackground = Color(0xFFE5E1E6)
val md_theme_dark_surface = Color(0xFF1B1B1F)
val md_theme_dark_onSurface = Color(0xFFE5E1E6)
val md_theme_dark_surfaceVariant = Color(0xFF46464F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC7C5D0)
val md_theme_dark_outline = Color(0xFF91909A)
val md_theme_dark_inverseOnSurface = Color(0xFF1B1B1F)
val md_theme_dark_inverseSurface = Color(0xFFE5E1E6)
val md_theme_dark_inversePrimary = Color(0xFF3E4ADE)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFBEC2FF)


val seed = Color(0xFF000EB9)
